public enum AutoCorrectionStarterCatalog {
    public static let rules: [AutoCorrectionRule] = [
        // Independently authored wrong-layout Russian words typed on an English keyboard.
        AutoCorrectionRule(trigger: "ghbdtn", replacement: "привет"),
        AutoCorrectionRule(trigger: "gjrf", replacement: "пока"),
        AutoCorrectionRule(trigger: "cgfcb,j", replacement: "спасибо"),
        AutoCorrectionRule(trigger: "bpdbyb", replacement: "извини"),
        AutoCorrectionRule(trigger: "lf", replacement: "да"),
        AutoCorrectionRule(trigger: "ytn", replacement: "нет"),
        AutoCorrectionRule(trigger: "[jhjij", replacement: "хорошо"),
        AutoCorrectionRule(trigger: "gkj[j", replacement: "плохо"),
        AutoCorrectionRule(trigger: "gj;fkeqcnf", replacement: "пожалуйста"),
        AutoCorrectionRule(trigger: "cjdctv", replacement: "совсем"),
        AutoCorrectionRule(trigger: "ctqxfc", replacement: "сейчас"),
        AutoCorrectionRule(trigger: "gjxtve", replacement: "почему"),
        AutoCorrectionRule(trigger: "rjulf", replacement: "когда"),
        AutoCorrectionRule(trigger: "rfrjq", replacement: "какой"),
        AutoCorrectionRule(trigger: "rjnjhjq", replacement: "которой"),
        AutoCorrectionRule(trigger: "vtyz", replacement: "меня"),
        AutoCorrectionRule(trigger: "nt,z", replacement: "тебя"),
        AutoCorrectionRule(trigger: "vjq", replacement: "мой"),
        AutoCorrectionRule(trigger: "ndjq", replacement: "твой"),
        AutoCorrectionRule(trigger: "levf.", replacement: "думаю"),
        AutoCorrectionRule(trigger: "gjyzk", replacement: "понял"),
        AutoCorrectionRule(trigger: "gjyzkf", replacement: "поняла"),
        AutoCorrectionRule(trigger: "hfccrfp", replacement: "рассказ"),
        AutoCorrectionRule(trigger: "hf,jnf", replacement: "работа"),
        AutoCorrectionRule(trigger: "ntcn", replacement: "тест"),
        AutoCorrectionRule(trigger: "rjl", replacement: "код"),
        AutoCorrectionRule(trigger: "jib,rf", replacement: "ошибка"),
        AutoCorrectionRule(trigger: "ghj,ktvf", replacement: "проблема"),
        AutoCorrectionRule(trigger: "htitybt", replacement: "решение"),
        AutoCorrectionRule(trigger: "jndtn", replacement: "ответ"),
        AutoCorrectionRule(trigger: "df;yj", replacement: "важно"),
        AutoCorrectionRule(trigger: "yjhvfkmyj", replacement: "нормально"),
        AutoCorrectionRule(trigger: "cdj,jlf", replacement: "свобода"),
        AutoCorrectionRule(trigger: "ghjcnj", replacement: "просто"),
        AutoCorrectionRule(trigger: "gjckt", replacement: "после"),
        AutoCorrectionRule(trigger: "ltymub", replacement: "деньги"),

        // Common English typos, case-insensitive and case-preserving.
        AutoCorrectionRule(trigger: "teh", replacement: "the", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "adn", replacement: "and", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "recieve", replacement: "receive", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "seperate", replacement: "separate", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "occured", replacement: "occurred", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "adress", replacement: "address", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "definately", replacement: "definitely", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "enviroment", replacement: "environment", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "langauge", replacement: "language", matchMode: .caseInsensitive),
        AutoCorrectionRule(trigger: "becuase", replacement: "because", matchMode: .caseInsensitive)
    ]
}
